os: Visual Studio 2019

install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk13
  - cmd: SET PATH=C:\ant\apache-ant-1.10.7\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: echo %USERPROFILE%
  - cmd: echo %PATH%
  - cmd: java -version

build_script:
  - gradlew.bat build

test_script:
  - gradlew.bat test
